config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :users

  root 'pages#index'

  get 'signup', 	 to: 'users#new', 				     as: 'signup'
  get 'login', 		 to: 'user_sessions#new', 		 as: 'login'
  post 'login', 	 to: 'user_sessions#create', 	 :via => :post
  delete 'logout', to: 'user_sessions#destroy',  as: 'logout'
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :user
  mount_uploader :product_image, AvatarUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :products
  has_secure_password

  def admin?
    self.role == 'admin'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
    end
  end

  def require_admin
    if current_user
      redirect_to root_path, notice: "You must be admin to access that page." unless current_user.admin?
    else
      redirect_to login_path, notice: "You must be logged in to access that page." unless current_user
    end
  end

  def require_user
    redirect_to login_path unless current_user
  end

  def redirect_logged_in
    redirect_to root_path if current_user
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  	@products = Product.all
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :require_user, except: [:index]
  before_action :require_admin, except: [:index, :show]
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    redirect_to root_path
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = current_user.products.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = current_user.products.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = current_user.products.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:product_name, :product_image, :product_price, :product_description, :user_id)
    end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  before_action :redirect_logged_in, only: [:new, :create]
  before_action :require_user, only: [:destroy]

  def create
  	@user = User.find_by_email(params[:session][:email])
  	if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
  	  redirect_to root_path
  	else
  	  redirect_to login_path, notice: 'Account or Password is incorrect'
    end
  end

  def destroy
  	session[:user_id] = nil
  	reset_session
    redirect_to login_path, notice: "You have been logged out."
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user, only: [:show, :edit, :update, :destroy]  
  before_action :correct_user, only: [:show, :edit, :update, :destroy]  

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to root_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to root_path, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def correct_user
      @user = User.find_by_id(params[:id])
      if @user == @current_user          
      else
        render_404
      end    
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:full_name, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header_logged_in.html.erb
<!-- Navigation -->
<nav class="navbar navbar-default">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header page-scroll">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<%= root_path %>">My application</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-left">
                <li class="hidden">
                    <a href="#page-top">+++++</a>
                </li>
                <li class="page-scroll">
                    <%= link_to 'New Product', new_product_path if current_user && current_user.admin? %>
                </li>
                <!--<li class="page-scroll">
                    <a href="#contact">Contact</a>
                </li>-->
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li class="hidden">
                    <a href="#page-top"></a>
                </li>
                <li class="page-scroll">
                    <%= link_to "#{current_user.full_name}", edit_user_path(current_user) %>
                </li>
                <li class="page-scroll">
                    <%= link_to "Sign Out", logout_path, method: :delete, class: "icon-signout hide-text" %>
                </li>
                <!--<li class="page-scroll">
                    <a href="#contact">Contact</a>
                </li>-->
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/layouts/_header_logged_out.html.erb
<!-- Navigation -->
<nav class="navbar navbar-default">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header page-scroll">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<%= root_path %>">My application</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li class="hidden">
                    <a href="#page-top"></a>
                </li>
                <li class="page-scroll">
                    <%= link_to 'Login', login_path %>
                </li>
                <li class="page-scroll">
                    <%= link_to 'Register', new_user_path %>  
                </li>
                <!--<li class="page-scroll">
                    <a href="#contact">Contact</a>
                </li>-->
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body id="page-top" class="index">

<% if current_user %>
<%= render :partial => 'layouts/header_logged_in' %>
<% else %>
<%= render :partial => 'layouts/header_logged_out' %>
<% end %>

<section id="yield">
<div class="container-fluid">
	<%= yield %>
</div>
</section>

</body>
</html>

app/views/pages/index.html.erb
<p id="notice"><%= notice %></p>

<article id="main" class="main col-md-12">  
  <div class="row">
    <% @products.each do |product| %>   
      <a href="<%= product_path(product) %>">
        <div class="col-md-3">
          <div class="review">    
            <%= image_tag product.product_image, :width => '75%', :height => '225' %>
          </div>               
          <h3><%= product.product_name %></h3>
          <h4>Giá: <%= product.product_price %> ₫</h4>   
          <h6><%= link_to 'Edit', edit_product_path(product) if current_user && current_user.admin? %></h6>
          <h6><%= link_to 'Destroy', product , method: :delete, data: { confirm: 'Are you sure?' } if current_user && current_user.admin? %></h6>  
        </div>
      </a>  
    <% end %>
  </div>
</article>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_name %><br>
    <%= f.text_field :product_name %>
  </div>
  <div class="field">
    <%= f.label :product_image %><br>
    <%= f.file_field :product_image %>
  </div>
  <div class="field">
    <%= f.label :product_price %><br>
    <%= f.text_field :product_price %>
  </div>
  <div class="field">
    <%= f.label :product_description %><br>
    <%= f.text_area :product_description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product name:</strong>
  <%= @product.product_name %>
</p>

<p>
  <strong>Product image:</strong>
  <%= @product.product_image %>
</p>

<p>
  <strong>Product price:</strong>
  <%= @product.product_price %>
</p>

<p>
  <strong>Product description:</strong>
  <%= @product.product_description %>
</p>

<%= link_to 'Back', products_path %>

app/views/user_sessions/new.html.erb
<% @title = 'Login' %>
<h3 style="text-align:center"><%= notice %></h3>

<%= form_for(:session, url: login_path, :html => { :class => 'form-signin' } ) do |f| %>

  <h2 class="form-signin-heading">Please sign in</h2>
  <label for="inputEmail" class="sr-only">Email address:</label>
  <%= f.email_field :email, :placeholder => "Email address", :id => "inputEmail", :class => "form-control", :required => true, :autofocus => true %>

  <label for="pwd" class="sr-only">Password:</label>
  <%= f.password_field :password, :placeholder => "Password", :id => "inputPassword", :class => "form-control" %>

  <div class="checkbox">
    <label>
      <%= check_box_tag :remember_me %> Remember me
    </label>
  </div>
  <%= f.submit "Log in", :class => "btn btn-lg btn-primary btn-block" %>

<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :full_name %><br>
    <%= f.text_field :full_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Full name:</strong>
  <%= @user.full_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>